"""empty message

Revision ID: c4a2fc39edba
Revises: 34e5e0968ca5
Create Date: 2023-04-06 16:42:29.971011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a2fc39edba'
down_revision = '34e5e0968ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_info', schema=None) as batch_op:
        batch_op.alter_column('serial_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car_info', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('serial_number',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
